from pathlib import Path

path = Path("tools/build_revp3_roadqa.py")
text = path.read_text(encoding="utf-8")

start = text.find("def _conforming_watertight_solid(\n")
end = text.find("\ndef solid_from_polygon", start)
if start < 0 or end < 0:
    raise RuntimeError("Rev.P5 road solid function not found")

replacement = r'''def _conforming_watertight_solid(
    component: Polygon,
    z_function: Callable[[float, float], float],
    thickness: float,
    max_edge: float,
) -> trimesh.Trimesh:
    """Build one closed, quality-controlled road/apron solid.

    A constrained Delaunay triangulation is generated by the compiled Triangle
    engine.  The maximum triangle area is tied to the requested mesh scale;
    therefore curves and junctions are refined without the exponential custom
    midpoint recursion that previously stalled the full model build.
    """
    if not component.is_valid:
        component = component.buffer(0)
    if component.is_empty or component.area <= 1.0e-8:
        raise RuntimeError("Cannot build a solid from an empty polygon")

    maximum_area = max(1.0, 0.45 * float(max_edge) ** 2)
    vertices_2d, faces_2d = trimesh.creation.triangulate_polygon(
        component,
        engine="triangle",
        triangle_args=f"pq28a{maximum_area:.6f}",
    )
    vertices_2d = np.asarray(vertices_2d, dtype=float)
    faces_2d = np.asarray(faces_2d, dtype=int)
    if vertices_2d.ndim != 2 or vertices_2d.shape[1] < 2:
        raise RuntimeError("Triangle returned invalid vertices")
    vertices_2d = vertices_2d[:, :2]
    if len(vertices_2d) < 3 or len(faces_2d) < 1:
        raise RuntimeError("Triangle returned no usable triangulation")

    # Remove only demonstrably degenerate triangles before extrusion.
    triangles = vertices_2d[faces_2d]
    signed_twice = (
        (triangles[:, 1, 0] - triangles[:, 0, 0])
        * (triangles[:, 2, 1] - triangles[:, 0, 1])
        - (triangles[:, 1, 1] - triangles[:, 0, 1])
        * (triangles[:, 2, 0] - triangles[:, 0, 0])
    )
    keep = np.abs(signed_twice) > 1.0e-12
    faces_2d = faces_2d[keep]
    if len(faces_2d) == 0:
        raise RuntimeError("All Triangle faces were degenerate")
    if float(np.median(signed_twice[keep])) < 0.0:
        faces_2d = faces_2d[:, ::-1]

    mesh = trimesh.creation.extrude_triangulation(
        vertices=vertices_2d,
        faces=faces_2d,
        height=float(thickness),
    )
    vertices = np.asarray(mesh.vertices, dtype=float)
    local_z = vertices[:, 2].copy()
    profile_z = np.asarray(
        [z_function(float(x), float(y)) for x, y in vertices[:, :2]],
        dtype=float,
    )
    vertices[:, 2] = profile_z - float(thickness) + local_z
    mesh.vertices = vertices
    mesh.remove_unreferenced_vertices()
    trimesh.repair.fix_normals(mesh, multibody=True)

    edge_rows = np.sort(np.asarray(mesh.edges, dtype=int), axis=1)
    _, edge_counts = np.unique(edge_rows, axis=0, return_counts=True)
    open_or_nonmanifold = int(np.count_nonzero(edge_counts != 2))
    if open_or_nonmanifold != 0 or not mesh.is_watertight:
        raise RuntimeError(
            "Triangle-extruded road solid is not watertight: "
            f"open/non-manifold edges={open_or_nonmanifold}"
        )
    if not mesh.is_winding_consistent:
        raise RuntimeError("Triangle-extruded road solid has inconsistent winding")
    return mesh
'''

path.write_text(text[:start] + replacement + text[end:], encoding="utf-8")
print("REV_P5_TRIANGLE_MESHING_PATCHED")
